### ISSUE TITLE
Transfer to another organization?

### ISSUE THREAD

**Issue by maelle** [ropensci/statistical-software-review-book#34]
ropensci-review-tools?

It took me a short while to find the repo. :sweat_smile:

**Comment by mpadge** [comment]
Moving would certainly be good, but i don't think that is the place. The `ropensci-review-tools` org really is just that, and those are intended for general use, and not specific to stats at all. Plus this repo should be renamed to `stats-devguide`, for which it seems to me that `ropensci/devguide` should be accompanied by `ropensci/stats-devguide`?

**Comment by maelle** [comment]
yep sounds good! Do not forget to update the repo in `_output.yml` :slightly_smiling_face:
