### ISSUE TITLE
Bayesian standards contain wrong tags (B31.2a instead of BS1.2a)

### ISSUE THREAD

**Issue by helske** [ropensci/statistical-software-review-book#54]
Running `pkgcheck` failed for me with Bayesian standards with error `Error: There are no standards with prefix [B]`, which seems to be caused by a few typos in the standards, starting from line 102:
https://github.com/ropensci/statistical-software-review-book/blob/1ea36b18d1c3fd7811a065d988e1ae98b8af3a8d/standards/bayesian.Rmd#L102

B31.2a should be BS1.2a, and similarly for b and c. Another minor issue, the next standard BS1.3 is not indented correctly.

**Comment by mpadge** [comment]
Thanks @helske, I've been meaning to enquire about your status. Great to have you back engaged here! Would you be willing to submit a pull request to fix?

**Comment by helske** [comment]
Just made a PR, forgot to tag correctly to this though. I'm pretty close to submitting the `bssm` package, just a few more standards to check out!
